version: '3'
services:
    app:
        build: .
        image: lapis:latest
        ports:
            - 8080:8080
        volumes:
            - .:/app
        environment:
            - LAPIS_ENVIRONMENT=production
            - PORT=8080
            - DATABASE_URL=postgresql://postgres:password@postgres/postgres
            - DATABASE_HOST=postgres
            - DATBASE_USER=postgres
            - DATABASE_PASSWORD=password
            - DATABASE_NAME=postgres
    postgres:
        image: postgres:11-alpine
        ports:
            - 5432:5432
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_PASSWORD: password
